export { default as FarmerListView } from './farmer-list-view'
export {default as FarmerRegEditView} from './farmer-reg-edit-view'
export { default as FarmerRegCreateView} from './farmer-reg-create-view'
export {default as FarmerCombineDetailsView} from './farmer-details-view'
// export { default as CattleCombineDetailsView } from './cattle-details-view'