export const statesOfIndia = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Andaman and Nicobar Islands',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Chandigarh',
  'Delhi',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Jammu and Kashmir',
  'Karnataka',
  'Kerala',
  'Lakshadweep',
  'Ladakh',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Puducherry',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];
