import {MD3DarkTheme, MD3LightTheme} from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  roundness: 2,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#F1CB41',
    accent: '#FF8C42',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    text: '#543310',
    placeholder: '#A68A56',
    backdrop: 'rgba(241, 203, 65, 0.2)',
    border: 'rgba(241, 203, 65, 0.3)',
    borderColor: '#F1CB41',

    onPrimary: '#FFFFFF',
    onAccent: '#333333',
    onBackground: '#333333',
    onSurface: '#333333',
    onPlaceholder: '#666666',
    onBackdrop: '#FFFFFF',

    secondary: '#FF6B6B',
    onSecondary: '#FFFFFF',
    error: '#FF5252',
    onError: '#FFFFFF',
    warning: '#FFC107',
    onWarning: '#333333',
    info: '#17A2B8',
    onInfo: '#FFFFFF',
    success: '#28A745',
    onSuccess: '#FFFFFF',
  },
  fonts: {
    bodyLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    default: {
      fontFamily: 'PublicSans-Regular',
      fontWeight: '400',
      letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 57,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 45,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 36,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 32,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 28,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 24,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 32,
    },
    labelLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 11,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    titleLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  roundness: 2,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#00A896',
    accent: '#FFD166',
    background: '#121212',
    surface: '#333333',
    text: '#FFFFFF',
    placeholder: '#CCCCCC',
    backdrop: 'rgba(255, 255, 255, 0.5)',
    border: 'rgba(209, 209, 209, 1)',
    borderColor: '#333333',

    onPrimary: '#FFFFFF',
    onAccent: '#333333',
    onBackground: '#CCCCCC',
    onSurface: '#FFFFFF',
    onPlaceholder: '#333333',
    onBackdrop: '#121212',

    secondary: '#FF6B6B',
    onSecondary: '#FFFFFF',
    error: '#FF5252',
    onError: '#FFFFFF',
    warning: '#FFC107',
    onWarning: '#333333',
    info: '#17A2B8',
    onInfo: '#FFFFFF',
    success: '#28A745',
    onSuccess: '#FFFFFF',
  },
  fonts: {
    bodyLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    default: {
      fontFamily: 'PublicSans-Regular',
      fontWeight: '400',
      letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 57,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 45,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 36,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 32,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 28,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 24,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 32,
    },
    labelLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 11,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    titleLarge: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 22,
      fontWeight: '400',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'PublicSans-Regular',
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
  },
};
