export const tractorBrand = {
  'Mahindra & Mahindra': [
    'Mahindra 275 DI TU',
    'Mahindra Arjun Novo 605 DI-i',
    'Mahindra JIVO 245 DI',
  ],
  'TAFE (Massey Ferguson)': [
    'Massey Ferguson 1035 DI',
    'Massey Ferguson 241 DI',
    'Massey Ferguson 7250 DI',
  ],
  Sonalika: ['Sonalika DI 745 III', 'Sonalika DI 35 Rx', 'Sonalika DI 750 III'],
  'Escorts (Farmtrac)': ['Farmtrac 45', 'Farmtrac 60', 'Farmtrac 6055'],
  'John Deere': ['John Deere 5050D', 'John Deere 5310', 'John Deere 5105'],
  'New Holland': ['New Holland 3630 TX Plus', 'New Holland 3230 NX', 'New Holland 4710'],
  Kubota: ['Kubota MU4501', 'Kubota Neostar B2441', 'Kubota L4508'],
  Swaraj: ['Swaraj 735 FE', 'Swaraj 855 FE', 'Swaraj 724 XM'],
  'Indo Farm': ['Indo Farm 1026 NG', 'Indo Farm 3048 DI', 'Indo Farm 4175 DI'],
  Preet: ['Preet 6049', 'Preet 3549', 'Preet 7549'],
};

export const framerProductConditions = ['New', 'Used', 'Refurbished'];

export const engineTypes = ['Diesel', 'Gasoline', 'Electric'];

export const tractorTransmissionTypes = [
  'Manual',
  'Synchromesh',
  'Constant Mesh',
  'Partial Synchromesh',
  'Sliding Mesh',
  'Hydrostatic',
];

export const tractorTireTypes = [
  'Agricultural Tires',
  'Industrial Tires',
  'Turf Tires',
  'Radial Tires',
  'Bias-Ply Tires',
  'Flotation Tires',
  'Row Crop Tires',
  'Mud and Snow Tires',
];

export const combineHarvesterBrand = {
  'Mahindra & Mahindra': [
    'Mahindra Arjun 605 Combine Harvester',
    'Mahindra Arjun Novo 605 Combine Harvester',
  ],
  'TAFE (Massey Ferguson)': [
    'Massey Ferguson 5300 Combine Harvester',
    'Massey Ferguson 9000 Series Combine Harvester',
  ],
  Sonalika: ['Sonalika Tiger Combine Harvester', 'Sonalika Trakstar Combine Harvester'],
  'Escorts (Farmtrac)': [
    'Farmtrac Champion Combine Harvester',
    'Farmtrac Supermaxx Combine Harvester',
  ],
  'John Deere': ['John Deere W Series Combine Harvester', 'John Deere T Series Combine Harvester'],
  'New Holland': [
    'New Holland CR Series Combine Harvester',
    'New Holland CX Series Combine Harvester',
  ],
  Kubota: ['Kubota DC Series Combine Harvester', 'Kubota Pro 8010 Combine Harvester'],
  Swaraj: ['Swaraj DCX Combine Harvester', 'Swaraj 9000 Combine Harvester'],
  'Indo Farm': ['Indo Farm Reaper Combine Harvester', 'Indo Farm Prime Series Combine Harvester'],
  Preet: ['Preet 749 Combine Harvester', 'Preet 9870 Combine Harvester'],
};

export const combineHarvesterConditions = ['New', 'Used', 'Refurbished'];

export const combineHarvesterEngineTypes = ['Diesel', 'Gasoline', 'Electric'];

export const combineHarvesterTransmissionTypes = [
  'Manual',
  'Hydrostatic',
  'CVT (Continuously Variable Transmission)',
  'Automatic',
];

export const combineHarvesterTireTypes = [
  'Standard Tires',
  'Rice Tires',
  'Track Systems',
  'Dual Tires',
  'Flotation Tires',
];
export const modernAgricultureTools = [
  'Drones',
  'GPS Soil Mapping',
  'Automatic Irrigation Systems',
  'Precision Seeders',
  'Crop Sensors',
  'Robotic Milkers',
  'Smart Sprinklers',
  'Autonomous Tractors',
  'Field Monitoring Systems',
  'Soil Moisture Sensors',
  'Variable Rate Technology (VRT)',
  'Agri-Drones for Monitoring',
  'Greenhouse Automation Systems',
  'Yield Monitors',
  'Automatic Weeders',
  'Laser Scarecrows',
  'Soil Analyzers',
  'Livestock Monitoring Systems',
  'Farm Management Software',
  'Smart Greenhouses',
  'Remote Monitoring Systems',
  'Weather Forecasting Tools',
  'Biometric Sensors for Livestock',
  'Hydroponic Systems',
  'Aeroponic Systems',
  'IoT Sensors',
  'Nutrient Management Software',
  'Blockchain for Supply Chain Management',
  'Robotic Fruit Pickers',
  'Automated Guided Vehicles (AGVs)',
  'Soil Compaction Sensors',
  'Variable Rate Fertilizer Applicators',
  'Field Robots',
  'Electric Tractors',
  'Smart Beehives',
  'Smart Pest Management Systems',
  'Artificial Intelligence in Crop Management',
  'Remote Sensing Technology',
  'Digital Marketplace Platforms',
  'Crop Monitoring Satellites',
  'Automated Livestock Feeding Systems',
  'Precision Livestock Farming Tools',
  'Plant Phenotyping Tools',
  'Biochar Production Units',
  'Aquaponic Systems',
  'Blockchain-enabled Traceability Tools',
  'Drone Sprayers',
  'Smart Irrigation Controllers',
  'Predictive Analytics Tools',
  'Vertical Farming Systems',
  'Microbial Inoculants',
];

export const modernAgricultureToolApplications = [
  'Plowing, tilling, planting',
  'Harvesting crops',
  'Crop monitoring, spraying, mapping',
  'Soil analysis and mapping',
  'Water management',
  'Accurate seed planting',
  'Monitoring crop health',
  'Automated milking',
  'Efficient irrigation',
  'Automated field work',
  'Real-time field data',
  'Monitoring soil moisture',
  'Precision application of inputs',
  'Field surveillance and data collection',
  'Controlled environment farming',
  'Measuring crop yield',
  'Automated weed removal',
  'Bird control',
  'Nutrient and pH analysis',
  'Health and activity tracking',
  'Farm operations management',
  'Automated greenhouse control',
  'Remote field surveillance',
  'Weather prediction',
  'Animal health monitoring',
  'Soil-less farming',
  'Soil-less, air-based farming',
  'Connected farming devices',
  'Optimizing nutrient use',
  'Traceability and transparency',
  'Automated fruit harvesting',
  'Transporting goods on farms',
  'Monitoring soil density',
  'Precision fertilization',
  'Various field tasks automation',
  'Eco-friendly field work',
  'Bee colony monitoring',
  'Pest detection and control',
  'Data-driven crop decisions',
  'Large-scale field data collection',
  'Trading agricultural products',
  'Satellite imagery for crop analysis',
  'Controlled animal feeding',
  'Optimized livestock management',
  'Analyzing plant traits',
  'Biochar creation for soil improvement',
  'Combined fish and plant farming',
  'Supply chain transparency',
  'Aerial application of pesticides and fertilizers',
  'Water-saving irrigation',
  'Forecasting agricultural trends',
  'Indoor multi-level farming',
  'Enhancing soil microbiome',
];

export const powerSource = ['Diesel', 'Petrol', 'Electric', 'Hybrid', 'Hydraulic'];

export const sellerType = [
  'Modern Agricultural Tool',
  'Cultivation Equipment',
  'Irrigration System',
  'Combine Harvester',
  'Tractor',
];

export const cattleTypes = [
  'Dairy Cattle',
  'Beef Cattle',
  'Dual-Purpose Cattle',
  'Oxen',
  'Bulls',
  'Heifers',
  'Calves',
  'Steers',
  'Breeding Stock',
  'Water Buffalo',
  'Zebu',
  'Yak',
  'Jersey Cattle',
  'Holstein Friesian',
  'Brahman Cattle',
  'Hereford Cattle',
  'Angus Cattle',
];

export const cattleBreeds = [
  'Holstein Friesian',
  'Jersey',
  'Guernsey',
  'Ayrshire',
  'Brown Swiss',
  'Hereford',
  'Angus',
  'Brahman',
  'Charolais',
  'Simmental',
  'Limousin',
  'Red Poll',
  'Shorthorn',
  'Galloway',
  'Belted Galloway',
  'Texas Longhorn',
  'Brangus',
  'Santa Gertrudis',
  'Devon',
  'Dexter',
  'Belgian Blue',
  'Piedmontese',
  'Wagyu',
  'South Devon',
  'Norwegian Red',
  'Chianina',
  'Gelbvieh',
  'Murray Grey',
  'Beefmaster',
];
