export const employmentType = [
  'Employed',
  'Self Employed Bussiness',
  'Independent Worker',
  'Student',
  'Homemaker',
  'Unemployed',
];
export const education = [
  'Doctorate',
  'Post Graduate',
  'Under Graduate',
  'Intermidiate(10+2)',
  'Mertric(10th)',
  'other',
];
export const majorFieldsForDoctoral = [
  'Doctor of Philosophy (Ph.D./PhD)',
  'Doctor of Medicine (M.D./MD)',
  'Doctor of Dental Surgery (DDS)',
  'Doctor of Veterinary Medicine (DVM or VMD)',
  'Doctor of Jurisprudence (J.D/JD)',
  'Doctor of Education (EdD)',
  'Doctor of Design (DDes)',
  'Doctor of Fine Arts (DFA)',
  'Doctor of Nursing Science (DNS)',
  'Doctor of Theology (ThD)',
  'Doctor of Business Administration',
  'Doctor of Engineering',
  'Doctor of Social Science',
  'Doctor of Architecture',
  'Doctor of Divinity',
  'Doctor of Science',
];
export const majorFieldsForUnderGraduate = [
  'Bachelor of Arts (B.A)',
  'Bachelor of Science (B.S)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Fine Arts (BFA)',
  'Bachelor of Architecture (B.Arch)',
  'Bachelor of Science in Nursing (BSN)',
  'Bachelor of Applied Arts (BAA)',
  'Bachelor of Applied Science (BAS)',
  'Bachelor of Engineering (B.E)',
  'Bachelor of Computer Applications (BCA)',
  'Bachelor of Commerce (B.Com)',
  'Bachelor of Education (B.Ed)',
  'Bachelor of Social Work (BSW)',
  'Bachelor of Laws (LLB)',
  'Bachelor of Pharmacy (B.Pharm)',
  'Bachelor of Dental Surgery (BDS)',
  'Bachelor of Veterinary Science( BVSc)',
  'Bachelor of Physical Education (B.P.Ed)',
  'Bachelor of Library Science (B.Lib.Sc)',
  'Bachelor of Journalism and Mass Communication (BJMC)',
  'Bachelor of Hotel Management (BHM)',
  'Bachelor of Music (BMus)',
  'Bachelor of Animation (BAnim)',
  'Bachelor of Environmental Science (BES)',
  'Bachelor of Fashion Design (BFD)',
  'Bachelor of Agricultural Science (BASc)',
  'Bachelor of Film and Television (BF&TV)',
  'Bachelor of Occupational Therapy (BOT)',
  'Bachelor of Biotechnology (BBT)',
  'Bachelor of Social Science (BSS)',
  'Bachelor of Marine Science (BMS)',
  'Bachelor of Game Design (BGD)',
  'Bachelor of Forestry (BF)',
  'Bachelor of Divinity (BD)',
];
export const majorFieldsForPostGraduate = [
  'M.Tech (Master of Technology)',
  'M.E (Master of Engineering)',
  'M.Com (Master of Commerce)',
  'MBA (Master of Business Administration)',
  'M.A (Master of Arts)',
  'M.S.W (Master of Social Work)',
  'M.Sc (Master of Science)',
  'M.Phil (Master of Philosophy)',
  'M.Ed (Master of Education)',
  'LL.M (Master of Laws)',
  'M.P.H (Master of Public Health)',
  'M.S.N (Master of Science in Nursing)',
  'M.F.A (Master of Fine Arts)',
  'M.Arch (Master of Architecture)',
  'M.C.A (Master of Communication Arts)',
  'M.Sc (Master of Science) in Media and Communication',
  'M.Env (Master of Environmental Science)',
  'M.S (Master of Science) in Environmental Management',
];
export const Year = [
  2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
  2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030,
];
export const experienceYears = [
  { value: 0, label: 'Fresher' },
  { value: 1, label: '1 Year' },
  { value: 2, label: '2 Year' },
  { value: 3, label: '3 Year' },
  { value: 4, label: '4 Year' },
  { value: 5, label: '5 Year' },
  { value: 6, label: '6 Year' },
  { value: 7, label: '7 Year' },
  { value: 8, label: '8 Year' },
  { value: 9, label: '9 Year' },
  { value: 10, label: '10 Year' },
];
export const jobCategory = [
  'Engineering',
  'Information Technology',
  'Business and Management',
  'HealthCare & Biotechnology',
  'Education',
  'Hospitality and Tourism',
  'Transportation and Logistics',
  'Engineering and Construction',
  'Agriculture and Forestry',
  'Public Administration and Policy',
  'Customer Service and Support',
  'Sports and Fitness',
  'Real Estate',
  'Information Services',
  'Maritime and Marine Engineering',
  'Humanitarian Aid and International Development',
  'Fashion and Beauty',
  'Consulting',
  'Research and Development',
  'Supply Chain and Procurement',
  'Community and Social Services',
  'Architecture and Urban Planning',
  'Veterinary Services',
  'Forensic Science',
  'Art and Design',
  'Gaming and Entertainment',
  'Conflict Resolution and Mediation',
  'Emergency Services',
  'Fashion and Apparel',
  'Renewable Energy',
  'Digital Media and Content Creation',
  'Public Relations and Communications',
  'Automotive Industry',
  'Technical Writing and Documentation',
  'International Business and Trade',
  'Food and Beverage Industry',
  'Supply Chain Management',
  'Engineering Management & operations',
  'Interior Design',
  'Legal Services',
  'Robotics and Automation',
  'Tourism and Travel',
  'Labour & Workers',
  'Foreign Jobs',
  'Other',
];
