export const subjects = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'English',
  'Computer Science',
  'Social Studies',
  'History',
  'Geography',
  'Economics',
  'Political Science',
  'Business Studies',
  'Accountancy',
  'Environmental Science',
  'Psychology',
  'Sociology',
  'Fine Arts',
  'Music',
  'Dance',
  'Engineering Subjects',
  'Medical Subjects',
  'Law Subjects',
  'Management Subjects',
  'Languages (French, Spanish, etc.)',
  'General Knowledge',
  'Others',
];

export const streams = [
  'IIT-JEE',
  'NEET',
  'AIIMS',
  'JEE Main',
  'JEE Advanced',
  'BITSAT',
  'AIPMT',
  'CAT',
  'MAT',
  'XAT',
  'GMAT',
  'GRE',
  'CLAT',
  'UPSC',
  'SSC',
  'Banking Exams (IBPS, SBI PO, etc.)',
  'GATE',
  'NDA',
  'CDS',
  'RRB Exams',
  'CTET',
  'UGC NET',
  'TOEFL',
  'IELTS',
  'PTE Academic',
  'SAT',
  'ACT',
  'others',
];

export const timings = ['Morning', 'Afternoon', 'Evening'];

export const schoolFeeTypes = [
  'Tuition Fee',
  'Admission Fee',
  'Registration Fee',
  'Library Fee',
  'Laboratory Fee',
  'Sports Fee',
  'Transport Fee',
  'Computer Fee',
  'Examination Fee',
  'Development Fee',
  'Activity Fee',
  'Caution Deposit',
  'Hostel Fee',
  'Uniform Fee',
  'Books Fee',
  'Miscellaneous Fee',
  'Late Fee',
  'Annual Fee',
  'PTA Fee',
  'Term Fee',
];
